server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:\Users\JEF\Documents\GitHub\Grafana-Loki-Example\Source\Grafana-Promtail\positions.yaml # This location needs to be writeable by Promtail.

client:
  url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: access1
    static_configs:
    - labels:
        job: app1
        __path__: C:\Users\JEF\Documents\GitHub\Grafana-Loki-Example\Source\Python Logger\app1.log
    pipeline_stages:
      - regex:
          expression: "(?P<time>\\S+ *\\S+) - (?P<type>\\S+) - (?P<info>\\S+) - (?P<content>.*)"
      - labels:
          info:
          content: